package cn.itcast.yycg.business.system.entity;

// Generated 2015-9-17 11:20:18 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * SysRole generated by hbm2java
 */
public class SysRole implements java.io.Serializable {

	private String id;
	private String name;
	private String groupid;
	private String vchar1;
	private String vchar2;
	private String vchar3;
	private Dictinfo dictinfoByGroupid;
	private Set sysRoleMenus = new HashSet(0);
//	private Set sysUsers = new HashSet(0);
	private Set sysRolePermissions = new HashSet(0);

	public SysRole() {
	}

	

	public Dictinfo getDictinfoByGroupid() {
		return dictinfoByGroupid;
	}



	public void setDictinfoByGroupid(Dictinfo dictinfoByGroupid) {
		this.dictinfoByGroupid = dictinfoByGroupid;
	}



	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getGroupid() {
		return this.groupid;
	}

	public void setGroupid(String groupid) {
		this.groupid = groupid;
	}

	public String getVchar1() {
		return this.vchar1;
	}

	public void setVchar1(String vchar1) {
		this.vchar1 = vchar1;
	}

	public String getVchar2() {
		return this.vchar2;
	}

	public void setVchar2(String vchar2) {
		this.vchar2 = vchar2;
	}

	public String getVchar3() {
		return this.vchar3;
	}

	public void setVchar3(String vchar3) {
		this.vchar3 = vchar3;
	}



	public Set getSysRoleMenus() {
		return sysRoleMenus;
	}



	public void setSysRoleMenus(Set sysRoleMenus) {
		this.sysRoleMenus = sysRoleMenus;
	}



	public Set getSysRolePermissions() {
		return sysRolePermissions;
	}



	public void setSysRolePermissions(Set sysRolePermissions) {
		this.sysRolePermissions = sysRolePermissions;
	}

	
//	public Set getSysUsers() {
//		return this.sysUsers;
//	}
//
//	public void setSysUsers(Set sysUsers) {
//		this.sysUsers = sysUsers;
//	}


}
